Installer: Changed length of MCUytpe...

diff --git a/S60tty2tft b/S60tty2tft
--- a/S60tty2tft
+++ b/S60tty2tft
@@ -20,6 +20,18 @@ start() {
       exit 1
     fi
 
+    echo "CMDHWINF" > ${TTYDEV} ; read -t5 HWINF < ${TTYDEV}
+    case "${HWINF}" in
+      "")  echo "Couldn't gather hardware info. Exiting."
+	   exit 1
+	   ;;
+      
+
+
+    if [ "${HWINF}" = "" ]
+    fi
+
+
     if [[ -x ${DAEMONSCRIPT} ]]; then
       if [ -e /run/tty2tft-daemon.pid ] && [ -d /proc/$(</run/tty2tft-daemon.pid) ]; then
 	echo "${DAEMONNAME} already running"
